FLAGS=-Wall -Werror -rdynamic
SOURCES=../../logging/src/logging.c ../../hash/src/hash.c ../../others/src/others.c secure_stack.c
MAIN=example.c
EXECUTABLE=stack_example.out

all:
	gcc $(FLAGS) $(SOURCES) $(MAIN) -o $(EXECUTABLE)
